/*Sedes*/
INSERT INTO SEDES(CODIGO,DIRECCION,CIUDAD,PAIS) VALUES('001','Calle 234-45','BOGOTA','COLOMBIA');
INSERT INTO SEDES(CODIGO,DIRECCION,CIUDAD,PAIS) VALUES('002','Cra 15 No 78-9','BUCARAMANGA','COLOMBIA');

/*Personas*/
INSERT INTO PERSONAS (APELLIDOS,NOMBRES,DIRECCION,CIUDAD,CELULAR,EMAIL) VALUES('Rodriguez Moreno','Camilo Ernesto','Cra 21 No 34-11','Bucaramagna','314587956','crodrigr@gmail.co');
INSERT INTO PERSONAS (APELLIDOS,NOMBRES,DIRECCION,CIUDAD,CELULAR,EMAIL) VALUES('Rangel Caceres','Diego Fernando','Cra 33 No 48-96','Bucaramagna','320587988','drangel@gmail.co');
INSERT INTO PERSONAS (APELLIDOS,NOMBRES,DIRECCION,CIUDAD,CELULAR,EMAIL) VALUES('Camargo Gonzales','Juan Carlos','Clle 78 No 100-25','Bucaramagna','321587000','jcamargo@gmail.co');
INSERT INTO PERSONAS (APELLIDOS,NOMBRES,DIRECCION,CIUDAD,CELULAR,EMAIL) VALUES('Tarazona Perez','Diana Milena','Cra 26 No 78-63','Bucaramagna','301587123','dtarazona@gmail.co');
INSERT INTO PERSONAS (APELLIDOS,NOMBRES,DIRECCION,CIUDAD,CELULAR,EMAIL) VALUES('Dalila Cadena','Karlo Lizeth','car 178 No 98-65','Bucaramagna','305587357','kreyes@gmail.co');
INSERT INTO PERSONAS (APELLIDOS,NOMBRES,DIRECCION,CIUDAD,CELULAR,EMAIL) VALUES('Torres Serrano','Celina Maria','cra 11 No 8-9','Bucaramagna','3016587951','ctorres@gmail.co');

/*Socios*/
INSERT INTO SOCIOS (ID,SEDE_ID) VALUES(1,1);
INSERT INTO SOCIOS (ID,SEDE_ID) VALUES(2,1);

/*Bancos*/
INSERT INTO BANCOS(ID_SOCIO,TIPO_CUENTA,NUMERO,ESTADO) VALUES(1,'AHORROS','1800-9889-9',true);
INSERT INTO BANCOS(ID_SOCIO,TIPO_CUENTA,NUMERO,ESTADO) VALUES(2,'AHORROS','1900-9000-8',true);

/*Donaciones*//
INSERT INTO DONACIONES(ID_SOCIO,FECHA,CATEGORIA,VALOR) VALUES(1,'2023-11-19T12:30:00','COMPLETO',100);
INSERT INTO DONACIONES(ID_SOCIO,FECHA,CATEGORIA,VALOR) VALUES(1,'2022-11-19T12:30:00','COMPLETO',100);
INSERT INTO DONACIONES(ID_SOCIO,FECHA,CATEGORIA,VALOR) VALUES(1,'2021-11-19T12:30:00','MEDIO',50);
INSERT INTO DONACIONES(ID_SOCIO,FECHA,CATEGORIA,VALOR) VALUES(1,'2020-11-19T12:30:00','BASICO',30);
INSERT INTO DONACIONES(ID_SOCIO,FECHA,CATEGORIA,VALOR) VALUES(2,'2023-11-19T12:30:00','COMPLETO',100);
INSERT INTO DONACIONES(ID_SOCIO,FECHA,CATEGORIA,VALOR) VALUES(2,'2022-11-19T12:30:00','COMPLETO',100);

/*Refugios*/
INSERT INTO REFUGIOS(CODIGO,DIRECCION,CIUDAD,PAIS) VALUES('COL01','Cra 100 No 1-45','BOGOTA','COLOMBIA');
INSERT INTO REFUGIOS(CODIGO,DIRECCION,CIUDAD,PAIS) VALUES('COL02','Cra 100 No 30-63','BuCARAMANGA','COLOMBIA');
INSERT INTO REFUGIOS(CODIGO,DIRECCION,CIUDAD,PAIS) VALUES('COL04','Cra 100 No 89-23','BARRANQUILLA','COLOMBIA');
INSERT INTO REFUGIOS(CODIGO,DIRECCION,CIUDAD,PAIS) VALUES('ANGL01','Ave 1 No 52-3','GANDA','ANGOLA');
INSERT INTO REFUGIOS(CODIGO,DIRECCION,CIUDAD,PAIS) VALUES('ANGO02','Ave 20 No 17-100','SUMBE','ANGOLA');


/*Empleados*/
INSERT INTO EMPLEADOS(ID,SEDE_ID,CARGO,PROFESION,ESTADO) VALUES(3,1,'Director','Administrador',true);
INSERT INTO EMPLEADOS(ID,SEDE_ID,CARGO,PROFESION,ESTADO) VALUES(4,1,'Voluntario','Medico',true);
INSERT INTO EMPLEADOS(ID,SEDE_ID,CARGO,PROFESION,ESTADO) VALUES(5,1,'Voluntario','Enfermero',true);
INSERT INTO EMPLEADOS(ID,SEDE_ID,CARGO,PROFESION,ESTADO) VALUES(6,1,'Voluntario','Odontologo',true);


/*Envios*/

INSERT INTO ENVIOS(CODIGO,FECHA,ID_REFUGIO) VALUES('ENV001','2023-11-19',1);

/*DetalleEnvios*/
INSERT INTO DETALLES_ENVIO(ENVIO_ID,SEDE_ID,CATEGORIA,SUBCATEGORIA,DESCRIPCION,CANTIDAD,UNIDAD_MEDIDA) VALUES(1,1,'HUMANITARIA','MEDICOS','MEDICOS GENERALES',2,'PERSONAS');
INSERT INTO DETALLES_ENVIO(ENVIO_ID,SEDE_ID,CATEGORIA,SUBCATEGORIA,DESCRIPCION,CANTIDAD,UNIDAD_MEDIDA) VALUES(1,1,'HUMANITARIA','ENFERMERA','AUXILIARES DE ENFERMERIA',10,'PERSONAS');
INSERT INTO DETALLES_ENVIO(ENVIO_ID,SEDE_ID,CATEGORIA,SUBCATEGORIA,DESCRIPCION,CANTIDAD,UNIDAD_MEDIDA) VALUES(1,1,'HUMANITARIA','ODONTOLOGOS','ODOTOLGOS REHABILITACIÓN',2,'PERSONAS');
INSERT INTO DETALLES_ENVIO(ENVIO_ID,SEDE_ID,CATEGORIA,SUBCATEGORIA,DESCRIPCION,CANTIDAD,UNIDAD_MEDIDA) VALUES(1,2,'MATERIAL','MEDICINA','ACETAMINOFEN',10000,'PASTILLAS');
INSERT INTO DETALLES_ENVIO(ENVIO_ID,SEDE_ID,CATEGORIA,SUBCATEGORIA,DESCRIPCION,CANTIDAD,UNIDAD_MEDIDA) VALUES(1,2,'MATERIAL','ALIMENTO','ARROZ',1000,'KILOS');
INSERT INTO DETALLES_ENVIO(ENVIO_ID,SEDE_ID,CATEGORIA,SUBCATEGORIA,DESCRIPCION,CANTIDAD,UNIDAD_MEDIDA) VALUES(1,2,'MATERIAL','ALIMENTO','PANELA',5000,'KILOS');

/*Sede-Envios*/
INSERT INTO SEDE_ENVIOS(ENVIO_ID,SEDE_ID) VALUES(1,1);
INSERT INTO SEDE_ENVIOS(ENVIO_ID,SEDE_ID) VALUES(1,2);
